name: Lint Go Code

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: lint
      uses: golangci/golangci-lint-action@master
      with:
            # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
            version: v1.18
            github-token: ${{ secrets.github_token }}